import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "notely",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <header className="p-4 border-b">
          <h1 className="text-xl font-bold">Notely by Murtaza</h1>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
