import type { Metadata } from "next";
import "./globals.css";
import ThemeToggle from './ThemeToggle';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white">
        <header className="p-4 border-b">
          <ThemeToggle />
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
